env:
  commonjs: true
  es6: true
  node: true
  mocha: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
    "spaced-comment": 0,
    "indent": [2, 4],
    "no-unused-vars": 0,
    "camelcase": 0,
    "no-useless-constructor": 0
}
